print('Ingrese el monto que desea solicitar:')
monto_prestamo = int(input())
print('Qué quiere calcular?')
print('Escriba "m" - para conteo de meses \nEscriba "p" - para cuota mensual:')
tipo_de_calculo = input()
print('Ingrese la cantidad de meses deseada:')
duracion_deseada = int(input())
